exports.nsfw = require('./nsfw')
exports.shortener = require('./shortener')
exports.qr = require('./qr')
exports.lirik = require('./lirik')
exports.wiki = require('./wikipedia')
exports.kbbi = require('./kbbi')