exports.nsfw = require('./nsfw')
exports.shortener = require('./shortener')
exports.lirik = require('./lirik')
exports.wiki = require('./wikipedia')
exports.kbbi = require('./kbbi')
exports.bmkg = require('./bmkg')
exports.weeabo = require('./weeabo')
exports.medsos = require('./medsos')