exports.nsfw = require('./nsfw')
exports.weeaboo = require('./weeaboo')
exports.downloader = require('./downloader')
exports.fun = require('./fun')
exports.misc = require('./misc')
exports.toxic = require('./toxic')